# Generated by Django 2.0.1 on 2018-06-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctlelo', '0002_game_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
