# Generated by Django 2.0.1 on 2018-01-26 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bnet_name', models.CharField(max_length=100)),
                ('ctl_name', models.CharField(max_length=50)),
                ('ctl_url', models.URLField(max_length=100)),
                ('league', models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum'), (4, 'Diamond'), (5, 'Master'), (6, 'Grandmaster')])),
                ('race', models.CharField(choices=[('Z', 'Zerg'), ('P', 'Protoss'), ('T', 'Terran'), ('R', 'Random')], max_length=1)),
                ('is_captain', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_abrv', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Roster'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='players',
            field=models.ManyToManyField(to='ctl.Player'),
        ),
    ]
