# Generated by Django 2.0.1 on 2018-02-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0003_auto_20180211_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='is_admin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
