# Generated by Django 2.0.1 on 2018-02-28 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0004_captain_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ctl.Roster'),
        ),
    ]
