# Generated by Django 2.0.1 on 2018-03-02 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0006_auto_20180302_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 9, 0, 55, 308548, tzinfo=utc)),
        ),
    ]
