# Generated by Django 2.0.1 on 2018-03-02 10:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0007_maps_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='players',
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 10, 57, 16, 287120, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Lineup',
        ),
    ]
