# Generated by Django 2.0.1 on 2018-03-02 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0008_auto_20180302_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.ManyToManyField(to='ctl.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Roster')),
            ],
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 10, 59, 32, 182528, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lineup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Maps'),
        ),
    ]
