# Generated by Django 2.0.1 on 2018-03-02 11:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0009_auto_20180302_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 11, 1, 30, 409955, tzinfo=utc)),
        ),
    ]
