# Generated by Django 2.0.1 on 2018-03-02 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0010_auto_20180302_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='players',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='team',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='week',
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 18, 20, 18, 425877, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Lineup',
        ),
    ]
