# Generated by Django 2.0.1 on 2018-03-02 19:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0011_auto_20180302_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LineupPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ctl.Player')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 2, 19, 11, 49, 868136, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='lineup',
            name='players',
            field=models.ManyToManyField(to='ctl.LineupPlayer'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Roster'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Maps'),
        ),
    ]
