# Generated by Django 2.0.1 on 2018-04-02 22:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0013_auto_20180331_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 22, 40, 36, 180816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 22, 40, 36, 182603, tzinfo=utc)),
        ),
    ]
