# Generated by Django 2.0.1 on 2018-04-07 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0014_auto_20180402_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='ctl.Roster')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='ctl.Roster')),
            ],
        ),
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 18, 5, 28, 113805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 7, 18, 5, 28, 114923, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='matchup',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Maps'),
        ),
    ]
