# Generated by Django 2.0.1 on 2018-04-12 00:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0015_auto_20180407_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='wiki_name',
            field=models.CharField(default='change me', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 0, 21, 39, 779260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 0, 21, 39, 780458, tzinfo=utc)),
        ),
    ]
