# Generated by Django 2.0.1 on 2018-04-12 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0017_auto_20180412_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 10, 1, 25, 4341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 12, 10, 1, 25, 5535, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='roster',
            name='icon_url',
            field=models.URLField(),
        ),
    ]
