# Generated by Django 2.0.1 on 2018-06-05 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0019_auto_20180418_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctl.Roster'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 19, 48, 12, 306036, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 19, 48, 12, 307424, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 5, 19, 48, 12, 309527, tzinfo=utc)),
        ),
    ]
