# Generated by Django 2.0.1 on 2018-06-26 05:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0020_auto_20180605_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_rs', to='ctl.Roster')),
            ],
        ),
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 5, 50, 19, 287426, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 5, 50, 19, 289887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 5, 50, 19, 291943, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='resultset',
            name='team1_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_report_rs', to='ctl.MatchReport'),
        ),
        migrations.AddField(
            model_name='resultset',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_rs', to='ctl.Roster'),
        ),
        migrations.AddField(
            model_name='resultset',
            name='team2_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_report_rs', to='ctl.MatchReport'),
        ),
        migrations.AddField(
            model_name='resultset',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctl.Maps'),
        ),
    ]
