# Generated by Django 2.0.1 on 2018-07-13 13:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0022_auto_20180627_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captain',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ctl.Roster'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 13, 38, 0, 665441, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 13, 38, 0, 667874, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 13, 13, 38, 0, 669277, tzinfo=utc)),
        ),
    ]
