# Generated by Django 2.0.1 on 2018-09-02 21:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0023_auto_20180713_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 21, 45, 42, 247070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 21, 45, 42, 249019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 21, 45, 42, 251163, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum'), (4, 'Diamond'), (5, 'Master'), (6, 'Grandmaster'), (-1, 'Bench')]),
        ),
    ]
