# Generated by Django 3.0 on 2019-12-13 17:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ctl', '0025_auto_20180902_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 17, 29, 28, 582387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='maps',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 17, 29, 28, 583177, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='matchreport',
            name='submit_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 13, 17, 29, 28, 584261, tzinfo=utc)),
        ),
    ]
